name: Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  generated-includes:
    name: Check format, generated-includes presence and license presence in source code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run generated-include check
        run: python3 Scripts/check_inline_generated_cpp_includes.py

      - name: Run license-banner check
        run: python3 Scripts/check_license_banner.py

      - name: Run format check
        run: python3 Scripts/format.py --dry-run

      - name: Run documentation sync check
        run: python3 Scripts/sync_documentation_files.py --dry-run
